package:
  name: q2_perc_norm
  version: 2018.4.2

source:
  path: ../

# make noarch, architecture-independent
build:
    noarch: generic

# Add bioconda channel for biom
extra:
  channels:
    - conda-forge
    - bioconda

requirements:

  build:
    - python
    - setuptools

  run:
    - python
    # QIIME 2 things for the setup
    - qiime2 >=2018.4
    - q2-types
    # Other modules used in the actual code
    - biom-format
    - pandas
    - numpy
    - scipy


about:
  home: https://github.com/cduvallet/q2-perc-norm
  license: BSD-3-Clause
  license_family: BSD
